<center><h1>READING, RESIZING AND DISPLAYING OF AN IMAGE IN OPENCV</h1></center>

For complete programme open the link 👉🏻 https://github.com/rajeshrishi/open-cv

While there are a number of good libraries out there, OpenCV is the most popular and documented library for handling images.

In [1]:
# functions : cv2.imread(), cv2.imshow() , cv2.imwrite()

In [2]:
# To install
!pip install opencv-python

You should consider upgrading via the 'c:\users\rajesh rishi\anaconda3\python.exe -m pip install --upgrade pip' command.


In [3]:
# Import Library
import cv2
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
# View version number of cv2
cv2.__version__

'4.3.0'

In [5]:
# Read coloured image
img=cv2.imread("lion.jpg",1)
# 'imread' is the read the image syntax.
# '0' is for black and white images and '1' is for coloured images

<img src="https://raw.githubusercontent.com/rajeshrishi/open-cv/main/download.png" layout="centre">

cv2.IMREAD_COLOR : Loads a color image. Any transparency of image will be neglected. It is the default flag.

cv2.IMREAD_GRAYSCALE : Loads image in grayscale mode

cv2.IMREAD_UNCHANGED : Loads image without changing as such including alpha channel.

Note Instead of these three flags, you can simply pass integers 1, 0 or -1 respectively. 

<center><l1>lion.jpg</l1></center>

<img src="https://raw.githubusercontent.com/rajeshrishi/open-cv/main/lion.jpg" layout="centre">
This is how we sees the image.

In [6]:
img
# This is how machine sees a coloured image.

array([[[244, 243, 245],
        [244, 243, 245],
        [244, 243, 245],
        ...,
        [245, 247, 248],
        [245, 247, 248],
        [244, 246, 247]],

       [[244, 243, 245],
        [244, 243, 245],
        [244, 243, 245],
        ...,
        [245, 247, 248],
        [245, 247, 248],
        [244, 246, 247]],

       [[244, 243, 245],
        [244, 243, 245],
        [244, 243, 245],
        ...,
        [243, 246, 250],
        [243, 246, 250],
        [244, 245, 249]],

       ...,

       [[ 72, 136, 170],
        [ 69, 136, 169],
        [ 71, 136, 167],
        ...,
        [ 15,  69, 132],
        [ 14,  68, 133],
        [ 16,  68, 138]],

       [[ 73, 137, 167],
        [ 72, 138, 167],
        [ 72, 136, 166],
        ...,
        [ 16,  70, 131],
        [ 17,  68, 131],
        [ 20,  69, 137]],

       [[ 74, 137, 165],
        [ 72, 138, 163],
        [ 74, 138, 163],
        ...,
        [ 18,  70, 130],
        [ 18,  67, 129],
        [ 23,  71, 137]]

In [7]:
# Read Black and white image (grey scale)
img_b=cv2.imread("lion.jpg",0)

In [8]:
img_b
# This is how machine sees a black and white image.

array([[244, 244, 244, ..., 247, 247, 246],
       [244, 244, 244, ..., 247, 247, 246],
       [244, 244, 244, ..., 247, 247, 246],
       ...,
       [139, 138, 138, ...,  82,  81,  83],
       [139, 139, 138, ...,  82,  81,  84],
       [138, 138, 138, ...,  82,  80,  85]], dtype=uint8)

In [9]:
# Checking the shape of the elements

In [10]:
print(img.shape)
# here '3' means colour channel 'RGB'

(743, 1121, 3)


In [11]:
print(img_b.shape)

(743, 1121)


The matrix consist of 743 rows and 1121 columns 

In [12]:
# Display the image
cv2.imshow('lion', img)
# 'cv2.imshow' is the show the image syntax.
# 'lion'is the name of the window that is displayed when image is shown in.
cv2.waitKey(2000)
# 'cv2.waitKey' is used to wait for sometime.
cv2.destroyAllWindows()
# 'cv2.destroyAllWindow' is used to destroy the window after seeing.

Output

<img src="https://raw.githubusercontent.com/rajeshrishi/open-cv/main/Output.jpg" layout="centre">


In [13]:
# Resizing the image
resized_image=cv2.resize(img,(650,500))

In [14]:
# Output of resized image
cv2.imshow('lion',resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

Output

<img src="https://raw.githubusercontent.com/rajeshrishi/open-cv/main/output%20resize.jpg" layout="centre">

